version: '3'

services:

  elasticsearch:
    image: 'elasticsearch:7.10.1'
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - './elastic_data:/usr/share/elasticsearch/data:rw'
    environment:
      - discovery.type=single-node
